vich_uploader:
    db_driver: orm

    mappings:
        logo:
            uri_prefix: /pics/logo
            upload_destination: '%kernel.project_dir%/public/pics/logo'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
